#' Plots for Bayesian Models
#'
#' @docType package
#' @name bayesplot-package
#' @aliases bayesplot
#'
#' @import ggplot2 stats
#'
#' @description
#' The \pkg{bayesplot} package provides a variety of \pkg{ggplot2}-based
#' plotting functions for use after fitting Bayesian models (typically, though
#' not exclusively, via Markov chain Monte Carlo). The package is designed not
#' only to provide convenient functionality for users, but also a common set of
#' functions that can be easily used by developers working on a variety of
#' packages for Bayesian modeling, particularly (but not necessarily) packages
#' powered by \pkg{\link[rstan]{rstan}}. Examples of packages already (or soon
#' to be) using \pkg{bayesplot} are \pkg{rstan} itself, as well as the
#' \pkg{rstan}-dependent \pkg{rstanarm} and \pkg{brms} packages for applied
#' regression modeling.
#'
#'  \if{html}{
#'    \figure{bayesplot.png}{options: width="30\%" alt="Figure: bayesplot.png"}
#'    \figure{bayesplot2.png}{options: width="30\%" alt="Figure: bayesplot2.png"}
#'    \figure{bayesplot3.png}{options: width="30\%" alt="Figure: bayesplot3.png"}
#'  }
#'
#' @section Plotting functionality:
#' The plotting functions in \pkg{bayesplot} are organized into several modules:
#' \itemize{
#'   \item \strong{\link[=MCMC-overview]{MCMC}}: Visualizations of Markov chain
#'   Monte Carlo (MCMC) simulations generated by \emph{any} MCMC algorithm.
#'   There are also additional functions specifically for use with models fit
#'   using the \link[=NUTS]{No-U-Turn Sampler (NUTS)}.
#'   \item \strong{\link[=PPC-overview]{PPC}}:
#'   Graphical posterior predictive checks (PPCs).
#'   \item \strong{Prediction/forecasting}:
#'   (Coming in a future release) Plots designed to assist with out-of-sample
#'   prediction.
#' }
#'
#' @template seealso-theme
#' @template seealso-colors
#' @seealso \code{\link[ggplot2]{ggsave}} in \pkg{ggplot2} for saving plots.
#'
#' @examples
#' # A few quick examples (all of the functions have many examples
#' # on their individual help pages)
#'
#' # MCMC plots
#' x <- example_mcmc_draws(params = 5)
#' mcmc_intervals(x, prob = 0.5)
#' mcmc_intervals(x, regex_pars = "beta")
#'
#' color_scheme_set("purple")
#' mcmc_areas(x, regex_pars = "beta", prob = 0.8)
#'
#' color_scheme_set("mix-blue-red")
#' mcmc_trace(x, pars = c("alpha", "sigma"),
#'            facet_args = list(nrow = 2))
#'
#' color_scheme_set("brightblue")
#' mcmc_scatter(x, pars = c("beta[1]", "sigma"),
#'              transformations = list(sigma = "log"))
#'
#'
#' # Graphical PPCs
#' y <- example_y_data()
#' yrep <- example_yrep_draws()
#' ppc_dens_overlay(y, yrep[1:50, ])
#'
#' color_scheme_set("pink")
#' ppc_hist(y, yrep[1:8, ])
#' ppc_stat(y, yrep, stat = "median") + grid_lines()
#'
NULL
