#' Tidy parameter selection
#'
#' @name tidy-params
#' @md
#'
#' @description As of version `1.7.0`, __bayesplot__ allows the `pars` argument
#'   for [MCMC plots][bayesplot::MCMC-overview] to be used for so-called 'tidy'
#'   variable selection (in the style of the __dplyr__ package). The
#'   [`vars()`][dplyr::vars] function is re-exported from __dplyr__ for this
#'   purpose.
#'
#'   When using `pars` for tidy parameter selection, the `regex_pars` argument
#'   is ignored because __bayesplot__ supports using [tidyselect helper
#'   functions][tidyselect::select_helpers] (`starts_with()`, `contains()`, etc.)
#'   for the same purpose.
#'
#' @examples
#'
#' x <- example_mcmc_draws(params = 6)
#' dimnames(x)
#' mcmc_hex(x, pars = vars(alpha, `beta[2]`))
#' mcmc_dens(x, pars = vars(sigma, contains("beta")))
#' mcmc_hist(x, pars = vars(-contains("beta")))
#'
#' \donttest{
#' if (requireNamespace("rstanarm", quietly = TRUE)) {
#'   fit <- example("example_model", package = "rstanarm", local=TRUE)$value
#'   posterior <- as.matrix(fit)
#'   print(colnames(posterior))
#'
#'   color_scheme_set("brightblue")
#'
#'   mcmc_hist(posterior, pars = vars(size, period3))
#'   mcmc_hist(posterior, pars = vars(size, contains("period")))
#'   mcmc_hist(posterior, pars = vars(size, contains("period"), -period3),
#'             facet_args = list(ncol = 2))
#'
#'   mcmc_intervals(posterior, pars = vars(contains("herd")))
#'   mcmc_intervals(posterior, pars = vars(contains("herd"), -contains("Sigma")))
#'
#'   bayesplot_theme_set(ggplot2::theme_dark())
#'   color_scheme_set("viridisB")
#'   mcmc_areas_ridges(posterior, pars = vars(starts_with("b[")))
#'
#'   color_scheme_set("purple")
#'   mcmc_areas_ridges(posterior, pars = vars(starts_with("b["), -matches("[7-9]")))
#' }
#' }
#'
#'
NULL


# re-export vars for tidy parameter selection
#' @importFrom dplyr vars
#' @export
dplyr::vars


# internal ----------------------------------------------------------------

#' Internal function for tidy parameter selection
#'
#' This function is called internally by prepare_mcmc_array() if
#' the user's 'pars' argument is a quosure.
#'
#' @noRd
#' @md
#' @param complete_pars A character vector of all parameter names.
#' @param pars_list A list of columns generated by `vars()`.
#' @return Character vector of selected parameter names.
#'
tidyselect_parameters <- function(complete_pars, pars_list) {
  helpers <- tidyselect::vars_select_helpers
  pars_list <- lapply(pars_list, rlang::env_bury, !!! helpers)
  selected <- tidyselect::vars_select(.vars = complete_pars, !!! pars_list)
  if (!length(selected)) {
    stop("No parameters were found matching those names.", call. = FALSE)
  }
  return(unname(selected))
}
