on:
  workflow_dispatch:

name: Reverse dependency check

jobs:
  bayesplot-revdeps:
    uses: andrjohns/ci-scripts/.github/workflows/revdeps.yml@6f9ccc34cf8011288a00be060d01168448ed6c49
    with:
      package: bayesplot
      bayesplot-source: ${{ github.ref_name }}
